# Generated by Django 4.0.2 on 2022-03-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='workforce/static/workforce/default_profile.jpg', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=20)),
                ('members', models.ManyToManyField(to='workforce.User')),
            ],
        ),
    ]
