# Generated by Django 4.0.2 on 2022-03-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_alter_user_image_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=20)),
                ('members', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workforce.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
