# Generated by Django 4.0.2 on 2022-03-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0006_member_alter_task_user_alter_team_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
