# Generated by Django 4.0.2 on 2022-03-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_alter_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to=''),
        ),
    ]
