# Generated by Django 4.0.2 on 2022-04-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0011_remove_team_members_member_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('due_date', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
