# Generated by Django 4.0.2 on 2022-04-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0013_deliverables_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverables',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
