# Generated by Django 4.0.2 on 2022-04-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0014_deliverables_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverables',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
