# Generated by Django 4.0.2 on 2022-04-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0016_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='slug',
        ),
    ]
