# Generated by Django 4.0.2 on 2022-04-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0017_remove_announcement_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
    ]
