# Generated by Django 4.0.2 on 2022-04-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0021_rename_type_work_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
