# Generated by Django 4.0.2 on 2022-04-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0022_alter_work_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/default_profile.jpg', null=True, upload_to=''),
        ),
    ]
